### ISSUE TITLE
monospacifier

### ISSUE THREAD

**Issue by musm** [kiwi0fruit/open-fonts#15]
Try the following in atom or vs code using he robot mono chain and compare with the GIF provided in the repo  https://github.com/cpitclaudel/monospacifier

```
abcde  abcde  abcde  abcde
a ∈ e  a ∨ e  a ⬾ e  a ∘ e
abcde  abcde  abcde  abcde

A B C -- regular text
𝓐 𝓑 𝓒 -- bold calligraphy
𝕬 𝕭 𝕮 -- bold fraktur
⬲ ⩈ ⥵ -- wide symbols

(∧) ∷ 𝔹 → 𝔹 → 𝔹 -- multi-line
				-- comment

∀ x y z ∈ ℕ,
  x ≲ y ∧ y ≲ z
  ⇒ x ⪅ z

```

Does it make sense to try to monospacify the fallback chain

**Comment by kiwi0fruit** [comment]
It works fine for me:

![Untitled](https://user-images.githubusercontent.com/19735117/59973039-b509f200-95c3-11e9-9230-a678fafe5495.png)

**Comment by kiwi0fruit** [comment]
Please make sure to use the latest fallback chain from [here](https://github.com/kiwi0fruit/open-fonts#roboto-mono).

**Comment by musm** [comment]
Opps sorry for the noise. Seems like I might have not have had the latest versions of all the fonts  (kinda a pain to download individually again)
