### ISSUE TITLE
Add isFixedPitch flag to Robotization Mono

### ISSUE THREAD

**Issue by kiwi0fruit** [kiwi0fruit/open-fonts#3]
See discussion in https://github.com/kiwi0fruit/sugartex/issues/3

**Comment by kiwi0fruit** [comment]
won't fix

**Comment by kiwi0fruit** [comment]
I wanted to try the simplest way of monospacifying all roboto mono styles but this would require testing if this breaks hinting on Windows. I don't want to test it. So I'll only wait for upstream fix (see original issue).

**Comment by musm** [comment]
See https://github.com/google/fonts/pull/1824

**Comment by kiwi0fruit** [comment]
Yep. I'm aware of it and simply wait for it to be fixed some day.

**Comment by kiwi0fruit** [comment]
@musm By the way. Yesterday I cleaned build scripts and also made a fully monospacified version of Roboto Mono: [open_mono.zip](https://github.com/kiwi0fruit/open-fonts/files/3056963/open_mono.zip) (non-italic styles were also monospacified).

It may have hinting issues on Windows that I don't want to test yet. Also I have no idea how to set `isFixedPitch`. But may be FontForge sets it automatically. But probably not.

But still you can test if it solves `isFixedPitch` problem. If not then please provide me with info how to set it in FontForge.

**Comment by musm** [comment]
Are you sure you linked the correct zip file? I don't see the fonts monospacified

**Comment by kiwi0fruit** [comment]
I'm completely sure. And I see them to be monospacified. But I don't know if they have the right flag set.

**Comment by kiwi0fruit** [comment]
The easiest thing to try next is to completely monospacify the fonts from the linked PR as there is already the flag set.

**Comment by musm** [comment]
> The easiest thing to try next is to completely monospacify the fonts from the linked PR as there is already the flag set.

I totally agree with this approach. Google already patched the fonts, so it seems best to just use those and apply your script ontop

**Comment by kiwi0fruit** [comment]
Please test this: [OpenMono2.zip](https://github.com/kiwi0fruit/open-fonts/files/3060210/OpenMono2.zip)

By the way: how to test if the font has isFixedPitch? Should it work where Roboto Mono doesn't?

**Comment by musm** [comment]
I'm testing it in a console  see https://github.com/google/fonts/issues/225#issuecomment-243251620 

also https://github.com/google/fonts/issues/225#issuecomment-243246986 has patched fonts. 


Strange, the google patched fonts in the PR https://github.com/google/fonts/pull/1824  don't work in my example above. However, Roboto Mono for Powerline does work, which is available here https://github.com/yurakl/fonts/tree/master/RobotoMono

**Comment by musm** [comment]
So maybe it's best to just apply your script  to https://github.com/yurakl/fonts/tree/master/RobotoMono

**Comment by kiwi0fruit** [comment]
What's your example? I installed PuTTY and test if it's available there.

**Comment by musm** [comment]
I use julia and to test it, I do
```
julia> using LinearAlgebra
julia> A = randn(10,10)
julia> cholesky(A*A')
```

in a conemu console

**Comment by kiwi0fruit** [comment]
I've just tested. And apperently applying monospacifier break the flag. So I need to know how to set it back in FontForge...

**Comment by kiwi0fruit** [comment]
It finally works! At least in PuTTY. Try [this](https://github.com/kiwi0fruit/open-fonts/blob/master/Fonts/OpenMono.zip?raw=true).

**Comment by musm** [comment]
Hmmm, still doesn't show up in my test case. Very odd.

**Comment by kiwi0fruit** [comment]
I guess this is the same bug as in

> Strange, the google patched fonts in the PR google/fonts#1824 don't work in my example above.

**Comment by musm** [comment]
Sorry I thought you applied it to the  powerline patched fonts in  https://github.com/yurakl/fonts/tree/master/RobotoMono

**Comment by kiwi0fruit** [comment]
And. The last test: [OpenMono.zip](https://github.com/kiwi0fruit/open-fonts/blob/master/Fonts/OpenMono.zip?raw=true). I also set OS/2 PANOSE Proportion to Monospaced (in addition to isFixedPitch flag).

**Comment by musm** [comment]
Woot finally works!

**Comment by musm** [comment]
So google needs to also set  OS/2 PANOSE Proportion to Monospaced  in their patch!

**Comment by kiwi0fruit** [comment]
I guess somebody should tell them (not me).

**Comment by musm** [comment]
Yep.  BTW you had a test file that showed the difference between monospacified math and non monospacified font. Where is it available?

**Comment by kiwi0fruit** [comment]
I guess that was about monospacified fallback math font gif in the [monospacifier repo](https://github.com/cpitclaudel/monospacifier) (not my).

**Comment by musm** [comment]
NVM the demo is here https://github.com/cpitclaudel/monospacifier

**Comment by musm** [comment]
One strange thing with your font is that if I try to use with with cmd, the bold option is automatically selected. 
![image](https://user-images.githubusercontent.com/4319522/55833065-f3bffe00-5ae4-11e9-94ca-f981b3ffb42b.png)


See the bold togle box is selected (usually it allows you to select or unselect bold)

**Comment by musm** [comment]
This is not the case with other fonts where it is selectable, e.g. 
![image](https://user-images.githubusercontent.com/4319522/55833175-25d16000-5ae5-11e9-8de1-a5a82673c753.png)

**Comment by kiwi0fruit** [comment]
I reproduced the bug in the Git Bash terminal (with **all** options selected during installation).

Strange bug. Roboto Mono from Google Fonts doesn't has it.

**Comment by kiwi0fruit** [comment]
@musm Fixed this bug in this https://github.com/kiwi0fruit/open-fonts/issues/11

**Comment by musm** [comment]
do you have the latest zips?

**Comment by kiwi0fruit** [comment]
Same zips. I simply reinstalled the font. Just to make sure you can reinstall regular style alone. Tell me if it helped.

**Comment by musm** [comment]
Strange it now works if I delete them from the system and reinstall them! 

Great!

**Comment by kiwi0fruit** [comment]
I envy you. You actually can delete fonts :) I don't even remember when Windows 7 was capable of deleting a font that is nowhere used :)

**Comment by musm** [comment]
It's simple, they're stored in   `C:\Windows\fonts`

**Comment by kiwi0fruit** [comment]
I cannot even delete files without a hassle as Windows says that they are in use. And deleting files manually doesn't fix bugs that were caused by fonts installation. For example MS Office 2007 can't use Noto Sans italics if I install a full set of 9000 styles. But it worked when there were only 4 main styles... And I cannot revert to that state anymore.

**Comment by musm** [comment]
upgrade to windows 10 😉 , a lot has improved, especially in terms of the console, which is now usable 😄

**Comment by kiwi0fruit** [comment]
I guess I would jump to Ubuntu instead at January 14, 2020.

**Comment by musm** [comment]
One thing I am wondering. How hard is it to include a monolithic font with all the fallback fonts merged onto each other?

**Comment by kiwi0fruit** [comment]
It's techically feasible and I guess not that hard but I won't do that as I really like having the last two fallbacks DejaVu Sans Mono and STIX Two Math. The first one has a really good Unicode coverage and the second one gives the rest. But they have incompatible licenses so they cannot be merged together.

OFL only fonts can be merged but I prefer mixing differently licensed fonts in fallback chain.

**Comment by kiwi0fruit** [comment]
By the way: I renamed Open Mono to Robotization Mono.

**Comment by kiwi0fruit** [comment]
@musm By the way. I've seen your screenshots and considering your interest in Roboto Mono font I highly recommend give a try to [MacType](https://github.com/kiwi0fruit/open-fonts/blob/master/README.md#mactype). Roboto Mono looks a lot better with it. Also Consolas bigger font sizes start looking nice with it.

**Comment by musm** [comment]
Interesting. The software is causing me some slow downs, but my computer is old. It would be way better if MSFT gave us different font smoothing options. I don't hate cleartype, it definitely makes things easier to read at small sizes.

**Comment by kiwi0fruit** [comment]
I also didn't hate ClearType. Untill I experienced the difference. I prefer to get rid of small sizes instead of Using ClearType.

As about performance. You can try another mode instead of the default. If I remember correctly it's possible to not have MacType everywhere but instead start only desired apps with it (start MacType with the app path as first arg).
