### ISSUE TITLE
Consider replacing all Linus Libertini Greek letters with STIX2 ones

### ISSUE THREAD

**Issue by kiwi0fruit** [kiwi0fruit/open-fonts#8]
See https://github.com/kiwi0fruit/open-fonts/issues/5 for screenshots and https://github.com/libertinus-fonts/libertinus/issues/132 for discussion.

* Replace all Greek Unicode section all together in Linus Libertini and Linus Libertini Math with STIX2 one. Also replace Math Greek of different styles.
* Should be linear treansform for every R, I, B, BI styles and lowercase and uppercase.
* Replace double story g with single story one for italics (in default stylistic sets) https://github.com/libertinus-fonts/libertinus/issues/133
* As a bonus: monitore ы ь ъ like in https://github.com/libertinus-fonts/libertinus/issues/74

**Comment by back0up** [comment]
https://github.com/libertinus-fonts/libertinus/issues/132

**Comment by kiwi0fruit** [comment]
I guess I won't have motivation to fix it as I can always use Source Serif Pro with STIX Two Text fallback and STIX Two Math.
